# -*- coding: utf-8 -*-
"""PIOT_Cascading_Impact_NSF_workshop_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTtoYOCEQLS90u7kU25AochsplCBDxMV

# Cascading Impact of Scaled Acetaminophen Production Using PIOT Model D

This notebook performs a **demand-driven Leontief cascading-impact analysis** using a process-based Physical Input–Output Table (PIOT).

## Physical technical-coefficient matrix

For the intermediate transaction matrix \(Z\), the physical technical-coefficient matrix is:

$$
A = Z\hat{x}^{-1}
$$

where:

- \(A\) is the physical technical-coefficient matrix;
- \(Z\) is the intermediate material transaction matrix;
- \(x_j\) is the baseline gross output of industry \(j\); and
- \(\hat{x}\) is the diagonal matrix of baseline gross industry outputs.

Each technical coefficient is calculated as:

$$
a_{ij}
=
\frac{Z_{ij}}{x_j}
$$

where \(a_{ij}\) represents the amount of material supplied by industry \(i\) that is required to produce one unit of output from industry \(j\).

## Leontief inverse

The Leontief inverse is calculated as:

$$
L
=
(I-A)^{-1}
$$

where \(I\) is the identity matrix.

## Final-demand shock

For a change in final demand, \(\Delta d\), the total change in industry output is:

$$
\Delta x
=
L\Delta d
$$

where:

- \(\Delta d\) is the final-demand shock vector; and
- \(\Delta x\) is the resulting change in gross output across all modeled industries.

The scaled output vector is:

$$
x^{\mathrm{scaled}}
=
x^{0}
+
\Delta x
$$

where \(x^{0}\) is the baseline gross-output vector.

## Acetaminophen scaling options

The notebook supports two scaling modes.

### 1. Target APAP gross production

A desired annual acetaminophen production volume is specified:

$$
x_{\mathrm{APAP}}^{\mathrm{target}}
$$

The required change in acetaminophen gross output is:

$$
\Delta x_{\mathrm{APAP}}
=
x_{\mathrm{APAP}}^{\mathrm{target}}
-
x_{\mathrm{APAP}}^{0}
$$

When only acetaminophen final demand is changed, the required final-demand shock is calculated as:

$$
\Delta d_{\mathrm{APAP}}
=
\frac{
x_{\mathrm{APAP}}^{\mathrm{target}}
-
x_{\mathrm{APAP}}^{0}
}{
L_{\mathrm{APAP},\mathrm{APAP}}
}
$$

### 2. Percentage increase in APAP final demand

The acetaminophen final-demand shock may instead be specified as a percentage:

$$
\Delta d_{\mathrm{APAP}}
=
d_{\mathrm{APAP}}^{0}
\left(
\frac{p}{100}
\right)
$$

where \(p\) is the selected percentage increase.

## Supply-chain tier decomposition

The cascading impact is decomposed into successive supply-chain tiers:

$$
\Delta x
=
\underbrace{\Delta d}_{\text{Tier 0: own-demand effect}}
+
\underbrace{A\Delta d}_{\text{Tier 1: direct upstream effect}}
+
\underbrace{A^{2}\Delta d}_{\text{Tier 2: indirect effect}}
+
\underbrace{A^{3}\Delta d}_{\text{Tier 3: deeper indirect effect}}
+
\cdots
$$

The individual tier contributions are:

$$
t_{0}
=
\Delta d
$$

$$
t_{1}
=
A\Delta d
$$

$$
t_{2}
=
A^{2}\Delta d
$$

and, generally,

$$
t_{k}
=
A^{k}\Delta d
$$

The sum of all tiers converges to the Leontief result when the spectral radius of \(A\) is less than one:

$$
\sum_{k=0}^{\infty} A^{k}\Delta d
=
(I-A)^{-1}\Delta d
=
L\Delta d
$$

## Additional waste associated with scaling

If the baseline waste-output coefficient for industry \(j\) is:

$$
g_j
=
\frac{W_j^{0}}{x_j^{0}}
$$

then the additional waste associated with the production increase is estimated as:

$$
\Delta W_j
=
g_j\Delta x_j
$$

The scaled waste generation is:

$$
W_j^{\mathrm{scaled}}
=
W_j^{0}
+
\Delta W_j
$$

## Step 0 — Setup
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.patches import Patch
import io

mpl.rcParams.update({
    'font.family': 'sans-serif',
    'font.size': 9,
    'axes.linewidth': 0.6,
    'axes.edgecolor': '#333333',
    'axes.titleweight': 'bold',
    'legend.frameon': False,
    'figure.dpi': 130,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
})

"""## Step 1 — Upload your baseline PIOT

Upload a raw PIOT CSV (industries as both rows and columns, plus meta columns
`ROE`, `EXPORTS`, `FINAL_DEMAND`, `WASTE`, and meta rows `ROE`, `IMPORTS`,
`SLACK`).

"""

try:
    from google.colab import files
    print("Upload your baseline PIOT CSV (e.g. PIOT_ModelD_APAP_baseline.csv):")
    uploaded = files.upload()
    BASELINE_PATH = list(uploaded.keys())[0]
except ImportError:
    # Not running in Colab -- fall back to a local path.
    BASELINE_PATH = 'PIOT_ModelD_APAP_baseline.csv'
    print(f"Not running in Colab; expecting the file at ./{BASELINE_PATH}")

print(f"Using: {BASELINE_PATH}")

"""## Step 2 — Build the network (A matrix + Leontief inverse)

`a_ij = z_ij / x_j`, where `x_j` is industry j's total output (row sum across
all industries + ROE + EXPORTS + FINAL_DEMAND + WASTE).



"""

META_COLS = ['ROE', 'EXPORTS', 'FINAL_DEMAND', 'WASTE']


def load_piot(path):
    """Load a raw PIOT CSV, return (dataframe, list of industry names)."""
    df = pd.read_csv(path, index_col=0).fillna(0.0)
    industries = [c for c in df.columns if c not in META_COLS and not c.startswith('Unnamed:')]
    return df, industries


def build_network(df, industries, remove_self_loops=False):
    """
    Build Z, x0, A, L from a loaded PIOT dataframe.

    Returns a dict with keys: Z, x0, A, L, industries, spectral_radius,
    self_loop_coef.
    """
    Z = df.loc[industries, industries].values.astype(float)
    x0 = df.loc[industries, industries + META_COLS].sum(axis=1).values.astype(float)
    x0 = np.where(x0 == 0, 1e-9, x0)

    A = Z / x0[np.newaxis, :]
    self_loop_coef = np.diag(A).copy()  # always retained as a diagnostic

    if remove_self_loops:
         np.fill_diagonal(A, 0.0)

    n = len(industries)
    I = np.eye(n)
    spectral_radius = float(np.max(np.abs(np.linalg.eigvals(A))))
    if spectral_radius >= 1.0:
        raise ValueError(
            f"Spectral radius of A is {spectral_radius:.4f} >= 1: the Leontief "
            "inverse does not exist (network not productive). This usually "
            "means a cell is a genuine data error rather than real recycling "
            "-- run the outlier screen in Step 2b before assuming the network "
            "itself is at fault."
        )
    L = np.linalg.inv(I - A)

    return {'Z': Z, 'x0': x0, 'A': A, 'L': L, 'industries': industries,
            'spectral_radius': spectral_radius,'self_loop_coef': self_loop_coef}


df0, industries = load_piot(BASELINE_PATH)
net = build_network(df0, industries)

print(f"Network: {len(industries)} industries")
print(f"Spectral radius of A: {net['spectral_radius']:.4f}  (must be < 1)")

top_recyclers = sorted(zip(industries, net['self_loop_coef']), key=lambda t: -t[1])[:5]
print("\nTop within-industry recycling ratios (diagnostic only):")
for name, coef in top_recyclers:
    print(f"  {name}: a_jj = {coef:.4f}")

print(net['A'])



"""## Step 3 — Run a demand shock

Pick a target industry and a % increase in its final demand. Everything
downstream (industrial cascade, tiers, waste) follows from this one shock.

"""

TARGET_INDUSTRY = "Acetaminophen"   # change to any industry name in `industries`
PCT_INCREASE = 0.15                # 25% increase in final demand

def demand_shock(df, industries, net, target_industry, pct_increase):
    L = net['L']
    d0 = df.loc[industries, 'FINAL_DEMAND'].values.astype(float)
    idx = industries.index(target_industry)
    d1 = d0.copy()
    d1[idx] = d0[idx] * (1 + pct_increase)
    delta_d = d1 - d0

    delta_x = L @ delta_d
    out = pd.DataFrame({'industry': industries, 'x0_baseline': net['x0'], 'delta_x': delta_x}).set_index('industry')
    out['pct_change'] = 100 * out['delta_x'] / out['x0_baseline']
    return out, delta_d


results, delta_d = demand_shock(df0, industries, net, TARGET_INDUSTRY, PCT_INCREASE)
print(f"Total network Delta x from {int(PCT_INCREASE*100)}% shock to {TARGET_INDUSTRY}: "
      f"{results['delta_x'].sum():,.0f} kg\n")
results.reindex(results['delta_x'].abs().sort_values(ascending=False).index).head(15)

"""## Step 4 — Tier decomposition

Split the cascade by propagation depth (own demand / direct / indirect / deeper).
"""

def tier_decomposition(net, delta_d):
    A, L, industries = net['A'], net['L'], net['industries']
    delta_x = L @ delta_d
    A2 = A @ A
    tier0 = delta_d.copy()
    tier1 = A @ delta_d
    tier2 = A2 @ delta_d
    tier3plus = delta_x - (tier0 + tier1 + tier2)
    return pd.DataFrame({'industry': industries, 'tier0_own_demand': tier0, 'tier1_direct': tier1,
                          'tier2_indirect': tier2, 'tier3plus_indirect': tier3plus, 'total': delta_x}).set_index('industry')


tiers = tier_decomposition(net, delta_d)
tiers.reindex(tiers['total'].abs().sort_values(ascending=False).index).head(10)

"""## Step 5 — Waste cascade

Weight the output cascade by each industry's baseline waste intensity (kg waste / kg output).
"""

def waste_cascade(df, industries, net, delta_x):
    x0 = net['x0']
    waste0 = df.loc[industries, 'WASTE'].values.astype(float)
    waste_intensity = np.divide(waste0, x0, out=np.zeros_like(waste0), where=x0 > 0)
    delta_waste = delta_x * waste_intensity
    return pd.DataFrame({'industry': industries, 'waste_intensity': waste_intensity,
                          'delta_waste': delta_waste}).set_index('industry')


waste_df = waste_cascade(df0, industries, net, results['delta_x'].values)
print(f"Total system waste increase: {waste_df['delta_waste'].sum():,.0f} kg\n")
waste_df.reindex(waste_df['delta_waste'].abs().sort_values(ascending=False).index).head(10)

"""## Step 6 — Plot the results"""

top = results.reindex(results['delta_x'].abs().sort_values(ascending=False).index).head(12).iloc[::-1]

fig, ax = plt.subplots(figsize=(6, 4.2))
ax.barh(top.index, top['delta_x'], color='#1F6F5C', height=0.7, edgecolor='white', linewidth=0.5)
ax.set_xscale('symlog', linthresh=1)

# Enhanced styling for "Nature quality"
ax.set_xlabel(r'Incremental output, $\Delta x$ (kg)', fontsize=10)
ax.set_title(f'Cascading output impact of a {int(PCT_INCREASE*100)}% increase\nin {TARGET_INDUSTRY} final demand', fontsize=11, fontweight='bold')

ax.spines[['top', 'right']].set_visible(False)
ax.spines['left'].set_linewidth(1.0)
ax.spines['bottom'].set_linewidth(1.0)

ax.tick_params(axis='both', which='major', width=1.0, length=4, labelsize=9)

plt.tight_layout()
plt.savefig('fig_cascading_output.png', dpi=300, bbox_inches='tight')
plt.show()

top_t = tiers.reindex(tiers['total'].abs().sort_values(ascending=False).index).head(8).iloc[::-1]
tier_cols = ['tier0_own_demand', 'tier1_direct', 'tier2_indirect', 'tier3plus_indirect']

# Using a perceptually uniform colormap for better distinction
tier_colors = plt.cm.viridis(np.linspace(0.1, 0.9, len(tier_cols)))
tier_labels = ['Own demand', 'Direct supplier', 'Indirect', 'Deeper indirect']

fig, ax = plt.subplots(figsize=(6.4, 4))
left = np.zeros(len(top_t))
for col, color, label in zip(tier_cols, tier_colors, tier_labels):
    vals = top_t[col].values
    ax.barh(top_t.index, vals, left=left, color=color, height=0.62, label=label, edgecolor='white', linewidth=0.3)
    left += vals
ax.set_xscale('symlog', linthresh=1)
ax.set_xlabel(r'Contribution to $\Delta x$ (kg)')
ax.set_title('Tier decomposition of the cascading impact')
ax.spines[['top', 'right']].set_visible(False)
ax.legend(loc='lower right', fontsize=7.5)
plt.tight_layout()
plt.savefig('fig_tier_decomposition.png')
plt.show()

top_w = waste_df.reindex(waste_df['delta_waste'].abs().sort_values(ascending=False).index).head(10).iloc[::-1]
top_w = top_w[top_w['delta_waste'] > 0]

fig, ax = plt.subplots(figsize=(6, 3.8))
ax.barh(top_w.index, top_w['delta_waste'], color='#C4622D', height=0.6, edgecolor='white')
ax.set_xscale('log')
ax.set_xlabel('Incremental waste generation (kg, log scale)')
ax.set_title(f'Waste cascade from a {int(PCT_INCREASE*100)}% {TARGET_INDUSTRY} demand increase')
ax.spines[['top', 'right']].set_visible(False)
plt.tight_layout()
plt.savefig('fig_waste_cascade.png')
plt.show()

"""## Step 7 (optional) — All-industries structural multipliers

Since most industries in a PIOT often have zero baseline final demand, a
"% of current demand" shock is undefined for them. This computes the
scale-independent **total output multiplier** (backward linkage) for every
industry via a unit demand shock — the standard IO-theory approach.

"""

def all_industries_multipliers(net):
    L, industries = net['L'], net['industries']
    backward_raw = L.sum(axis=0)
    forward_raw = L.sum(axis=1)   # demand-side proxy for forward linkage
    self_effect = np.diag(L)
    return pd.DataFrame({
        'industry': industries,
        'backward_linkage_raw': backward_raw,
        'backward_linkage_norm': backward_raw / backward_raw.mean(),
        'forward_sensitivity_norm': forward_raw / forward_raw.mean(),
        'self_loop_coef': net['self_loop_coef'],
    }).set_index('industry').sort_values('backward_linkage_raw', ascending=False)


impact = all_industries_multipliers(net)
impact.head(15)

top_m = impact.sort_values('backward_linkage_raw', ascending=True).tail(20)

fig, ax = plt.subplots(figsize=(6.4, 6))
ax.barh(top_m.index, top_m['backward_linkage_raw'], color='#4C72B0', height=0.65, edgecolor='white')
ax.axvline(1.0, color='#333333', linewidth=0.7, linestyle='--')
ax.set_xlabel('Total output multiplier (backward linkage)')
ax.set_title('Cascading impact of every industry on the network\n(unit final-demand shock)')
ax.spines[['top', 'right']].set_visible(False)
plt.tight_layout()
plt.savefig('fig_all_industries_multipliers.png')
plt.show()

"""## Step 8 — Download results

Saves all result tables as CSV and zips the figures for download.

"""

results.to_csv('cascading_results.csv')
tiers.to_csv('tier_decomposition.csv')
waste_df.to_csv('waste_cascade.csv')
impact.to_csv('all_industry_multipliers.csv')

import zipfile
with zipfile.ZipFile('piot_cascade_outputs.zip', 'w') as zf:
    for fname in ['cascading_results.csv', 'tier_decomposition.csv', 'waste_cascade.csv',
                  'all_industry_multipliers.csv', 'fig_cascading_output.png',
                  'fig_tier_decomposition.png', 'fig_waste_cascade.png',
                  'fig_all_industries_multipliers.png']:
        try:
            zf.write(fname)
        except FileNotFoundError:
            pass

print("Saved piot_cascade_outputs.zip")

try:
    from google.colab import files
    files.download('piot_cascade_outputs.zip')
except ImportError:
    print("Not running in Colab -- find piot_cascade_outputs.zip in the working directory.")